### ISSUE TITLE
关于插件中错误提示的建议与解决方案

### ISSUE THREAD

**Issue by whosydd** [zeromicro/goctl-vscode#14]
刚刚接触go-zero，很抱歉我还是个强迫症，关于错误提示没有出现在`problems`中我很意外，所以我添加了这个功能

另外，我发现目前插件仅仅是简单的每次抛出一个错误，还需要使用**format**才可以触发插件提示，虽然我想参照[vscode-extension-samples](https://github.com/microsoft/vscode-extension-samples/blob/main/code-actions-sample/src/diagnostics.ts)中的例子进行更改，以实现实时监控的功能，但是很抱歉我失败了，因为我发现我没法把error暴露出来，又不想破坏原本的代码结构，也可能是因为我js学的不到位，始终没有做到。

所以，目前仅仅是简单的一条一条的处理错误信息。同时也希望你可以参考下[vscode-extension-samples](https://github.com/microsoft/vscode-extension-samples/blob/main/code-actions-sample/src/diagnostics.ts)，并完善该插件。

![image](https://raw.githubusercontent.com/whosydd/images-in-one/main/images/202210072226022.gif)

**Comment by jianfan-dev** [comment]
非常感谢你的建议与解决方案，近期我会抽时间研究一下并支持这个功能。

**Comment by jianfan-dev** [comment]
非常感谢你的提议！

目前 [goctl-vscode](https://github.com/zeromicro/goctl-vscode) 插件依赖 goctl 二进制文件来执行 format 和 problems 提示，暂不支持检测多个 problems 的检测。

#15  格式化代码后合并了，感谢支持。
