### ISSUE TITLE
api文件保存时文件头部会自动出现go: 'go mod init' accepts at most one argument

### ISSUE THREAD

**Issue by accaolei** [zeromicro/goctl-vscode#16]
vscode使用了goctl插件，.api文件保存的时候，第一行添加一样 go: 'go mod init' accepts at most one argument

**Comment by kesonan** [comment]
It has already fixed on  https://github.com/zeromicro/go-zero/pull/4176, you can upgrade your goctl to the master branch after it merged.

**Comment by jianfan-dev** [comment]
goctl [v1.6.6](https://github.com/zeromicro/go-zero/releases/tag/tools%2Fgoctl%2Fv1.6.6) version has fixed this problem.
