### ISSUE TITLE
vscode 设置"editor.formatOnSave": true,更改api自动保存顶部会出现go: malformed module path "/": trailing slash

### ISSUE THREAD

**Issue by iwalkerr** [zeromicro/goctl-vscode#17]
<img width="652" alt="image" src="https://github.com/zeromicro/goctl-vscode/assets/43042929/4252a5ae-eefe-4250-8fd2-48bf3116741c">

Environments (please complete the following information):

OS: [e.g. Mac]
go-zero version [e.g. go 1.22.0]
goctl version [e.g. 1.6.5, optional]

goctl-vscode [v0.1.10]

**Comment by CocoaLcc** [comment]
I also encountered the same problem, how to solve it?

**Comment by kesonan** [comment]
It has already fixed on  https://github.com/zeromicro/go-zero/pull/4176, you can upgrade your goctl to the master branch after it merged.

**Comment by jianfan-dev** [comment]
goctl [v1.6.6](https://github.com/zeromicro/go-zero/releases/tag/tools%2Fgoctl%2Fv1.6.6) version has fixed this problem.
