### ISSUE TITLE
[bug] 文件右键使用格式化代码提示无法从 path 找到 goctl

### ISSUE THREAD

**Issue by awsl1414** [zeromicro/goctl-vscode#20]
goctl-vscode version: 0.1.10
goctl version: 1.7.2 linux/amd64

报错内容：Check the console in goctl when formatting. goctl seem not in your $PATH , please try in terminal.

实际：
![image](https://github.com/user-attachments/assets/85a1d36b-4cba-45cc-b4cc-ed7913fa199b)

**Comment by jianfan-dev** [comment]
这个错误是由于 `nodejs` 执行 `child_process` 调用 `goctl` 命令时抛出的 "No such file or directory" 导致的。

建议检查下 vscode 环境变量。

另外 [goctl-vscode](https://github.com/zeromicro/goctl-vscode) 在初始化的时候也有打印 `$PATH` 环境变量，可以打开 vscode 的 `output` 面板，切换到 `Goctl` 查看插件识别到的 `$PATH` 环境变量 (终端的 `$PATH`环境变量和 vscode 插件识别到的可能不一致) ，并检查 `goctl` 命令行工具是否在 `$PATH` 环境变量所在的路径中。

`output` 面板输出的 `$PATH` 环境变量：

<img width="1344" alt="image" src="https://github.com/user-attachments/assets/24484cf3-3ecf-4ef0-88f9-09da75be0256">
