### ISSUE TITLE
Syntax highlighting is weird

### ISSUE THREAD

**Issue by bingoIsCoder** [zeromicro/goctl-vscode#9]
Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Goctl extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.16.7 darwin/amd64
* Run `goctl -v` to get version of Goctl from _the VS Code integrated terminal_.
	- goctl version 1.2.3 darwin/amd64
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.62.0
          b3318bc0524af3d74034b8bb8a64df0ccf35549a
          x64
* Check your installed extensions to get the version of the VS Code Goctl extension.
	- v0.1.8
* Check your OS version.
	- Mac 11.5.2 (20G95)

### Describe the bug
The syntax highlighting seems not working well regarding service code block 

### Steps to reproduce the behavior:
1. Create a api file (refer to [official document](https://go-zero.dev/cn/api-grammar.html?h=api))
2. Open the api file by vs code
3. See error

### Screenshots or recordings
![image](https://user-images.githubusercontent.com/22683240/141714736-5710b936-cd7a-482f-b924-4e5769bbd82e.png)

**Comment by jianfan-dev** [comment]
The problem is caused by a change in the format of the goctl `@doc` code block, which I will take the time to fix. 

You can start by using `@doc ()` to get the extension to recognize the syntax. 

Thanks for the feedback!
